# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  visualqna-xeon-backend-server:
    image: ${REGISTRY:-opea}/visualqna:${TAG:-latest}
    container_name: visualqna-xeon-backend-server
    ports:
      - "8888:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - LVM_SERVICE_HOST_IP=${REMOTE_ENDPOINT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ipc: host
    restart: always
  visualqna-xeon-ui-server:
    image: ${REGISTRY:-opea}/visualqna-ui:${TAG:-latest}
    container_name: visualqna-xeon-ui-server
    depends_on:
      - visualqna-xeon-backend-server
    ports:
      - "5173:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - BACKEND_BASE_URL=${BACKEND_SERVICE_ENDPOINT}
    ipc: host
    restart: always
  visualqna-xeon-nginx-server:
    image: ${REGISTRY:-opea}/nginx:${TAG:-latest}
    container_name: visualqna-xeon-nginx-server
    depends_on:
      - visualqna-xeon-backend-server
      - visualqna-xeon-ui-server
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - FRONTEND_SERVICE_IP=${FRONTEND_SERVICE_IP}
      - FRONTEND_SERVICE_PORT=${FRONTEND_SERVICE_PORT}
      - BACKEND_SERVICE_NAME=${BACKEND_SERVICE_NAME}
      - BACKEND_SERVICE_IP=${BACKEND_SERVICE_IP}
      - BACKEND_SERVICE_PORT=${BACKEND_SERVICE_PORT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
